name: Python CI with Docker

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: docker build -t ci-cd-python .

      - name: Ejecutar tests en Docker
        run: docker run ci-cd-python